### ISSUE TITLE
[Fix] Twitter icon should be changed to X icon

### ISSUE THREAD

**Issue by Kaniz-Fatma** [AIforDevs/website#2]
As Twitter is changed to X , the logo is also needed to be changed in homepage.

![Screenshot_2023-10-08-16-35-59-36_254de13a4bc8758c9908fff1f73e3725](https://github.com/AIforDevs/website/assets/146003237/e584d6b3-f72d-4ace-b30a-da5457147703)

**Comment by Dnyaneshvn** [comment]
@Kaniz-Fatma Hey! Thanks for creating this issue.

One thing I want to tell you is that it's really good practice to create an issue first. But, you should also come up with code, as many people are willing to help with that.

I'm going with @VivekYadav193's PR for now.

@adarshpathak3408 and @Kaniz-Fatma, please feel free to create new issues and PRs. There are a lot of changes that need to be made!

Keep it up, guys!

**Comment by Kaniz-Fatma** [comment]
Very sorry to say it but this should be my right to accomplish this task as I raised the issue very first. I was waiting to be assigned for this and this is totally unexpected that someone see this and come up with a pr. You can go ahead if it feels right thing to you.

**Comment by Dnyaneshvn** [comment]
Yes Kaniz,

I have seen this kind of scenarios in big organizations as well, but lastly
they're going with opened PR.

that's why I merged PR.

Our email ID is ***@***.*** .
you can create the same for that.
