### ISSUE TITLE
feat: Adding hover effect to the feature cards.

### ISSUE THREAD

**Issue by SujayShanbhag** [AIforDevs/website#5]
When the user hovers over a features, it slightly increases in size with a smooth transition effect, providing a subtle interactive feedback.

**Comment by SujayShanbhag** [comment]
I'd like to work on this feature.

**Comment by Dnyaneshvn** [comment]
Hi @SujayShanbhag,
Thanks for the feature card hover effect suggestion! ⭐ the repo?
